services:
  stac-dc:
    build: ./
    volumes:
      - type: bind
        source: ./
        target: /app
    restart: unless-stopped
#    logging:
#      - driver: "journald"
#      - options:
#          tag: "stac-dc"
#          labels: "app"
#    labels:
#      - "app=stac-dc"
